apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-project-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.project.slug }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              project: {{ .Values.project.slug }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-ingress-from-studio
  namespace: default
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.project.slug }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              web: studio-web
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-egress-to-studio
  namespace: default
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.project.slug }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              web: studio-web
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-egress-to-project
  namespace: default
spec:
  podSelector:
    matchLabels:
      project: {{ .Values.project.slug }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.project.slug }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-ingress-egress-studio-web-apps
  namespace: {{ .Values.namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      web: studio-web
  policyTypes:
    - Ingress
    - Egress
  ingress: 
  - from:
    - podSelector:
        matchLabels:
          project: {{ .Values.project.slug }}
  egress: 
  - to:
    - podSelector:
        matchLabels:
          project: {{ .Values.project.slug }}