namespace: default
appname: customapp
project:
  name: project
  slug: project-slug

global:
  protocol: TCP

apps:
  volumek8s:

resources:
  requests:
    ephemeral-storage: "50Mi"
    cpu: 1.0
  limits:
    ephemeral-storage: "400Mi"
    cpu: 1.0

appconfig:
  port: 8501

service:
  name: customapp-svc

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress
  
podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all
