apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: {{ .Values.appname }}
      project: {{ .Values.project.slug }}
      type: app
      pod: {{ .Values.appname }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: {{ .Values.appname }}
        project: {{ .Values.project.slug }}
        networking/allow-internet-egress: "false"
        type: app
        pod: {{ .Values.appname }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-s3
        image: busybox
        env:
        - name: S3_SERVICE
          value: "{{ .Values.s3.service }}"
        - name: S3_PORT
          value: "{{ .Values.s3.port }}"
        command:  ["sh", "-c", "until nc -z $S3_SERVICE $S3_PORT > /dev/null; do echo Waiting for master.; sleep 2; done;"]
      - name: create-bucket
        image: minio/mc
        env:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.service }}
              key: accesskey
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.service }}
              key: secretkey
        - name: S3_ENDPOINT
          value: "http://{{ .Values.s3.service }}:{{ .Values.s3.port }}"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "mc alias set projminio $S3_ENDPOINT $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY;mc mb projminio/mlflow || echo 'Bucket mlflow already exists'"]
      containers:
      - image: {{ .Values.appconfig.image }}
        imagePullPolicy: IfNotPresent
        name: mlflow
        command: ["/bin/bash"]
        args: ["-c", "mlflow server --backend-store-uri $BACKEND_STORE_URI --default-artifact-root s3://$MLFLOW_BUCKET/ --host 0.0.0.0 --port 5000"]
        ports:
        - containerPort: {{ .Values.appconfig.port }}
        env:
        - name: BACKEND_STORE_URI
          value: sqlite:///mlruns/mydb.sqlite
        - name: MLFLOW_BUCKET
          value: mlflow
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://{{ .Values.s3.service }}:{{ .Values.s3.port }}"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.service }}
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.service }}
              key: secretkey
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.flavor | nindent 10 }}
        volumeMounts:
        {{- range $key, $value := .Values.apps.volumeK8s }}
        - name: {{ $key }}
          mountPath: /mlruns
        {{- end }}
      hostname: {{ .Release.Name }}
      restartPolicy: Always
      volumes:
      - name: auth-vol
        emptyDir: {}
      - name: rp-conf
        configMap:
          name: {{ .Release.Name }}-rp-config
      {{- range $key, $value := .Values.apps.volumeK8s }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
