apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-ui
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-mlflow
    app: mlflow-ui
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.appconfig.uiport }}
    protocol: TCP
  selector:
    release: {{ .Release.Name }}
