apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ $.Release.Name }}
      app: wetty
      project: {{ $.Values.project.slug }}
      type: app
      pod: wetty
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        # prometheus.io/port: "8501"
      labels:
        release: {{ $.Release.Name }}
        app: wetty
        project: {{ $.Values.project.slug }}
        type: app
        pod: wetty
    spec:
    {{ if .Values.flavor.gpu.enabled }}
      affinity:
        {{ .Values.labs.affinity | toYaml | nindent 8 | trim }}
    {{ end }}
    {{ if .Values.environment.registry }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-pull-secret
    {{ end }}
      containers:
      - name: wetty
        image: scaleoutsystems/wetty:latest
        imagePullPolicy: IfNotPresent
        args:
          - --ssh-host=localhost
          - --ssh-port=22
          - --ssh-user=stackn
          - --ssh-key=/ssh-key
          - --ssh-auth=publickey
          - --force-ssh=true
          - --command=/bin/bash
        ports:
          - containerPort: 3000
      - name: ubuntu
        image: {{ .Values.environment.repository }}/{{ .Values.environment.image }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: {{ .Values.flavor.limits.memory }}
            cpu: {{ .Values.flavor.limits.cpu }}
            {{ if .Values.flavor.gpu.enabled }}
            nvidia.com/gpu: {{ .Values.flavor.requests.gpu }}
            {{ end }}
          requests:
            memory: {{ .Values.flavor.requests.memory }}
            cpu: {{ .Values.flavor.requests.cpu }}
            {{ if .Values.flavor.gpu.enabled }}
            nvidia.com/gpu: {{ .Values.flavor.requests.gpu }}
            {{ end }}
        lifecycle:
          postStart:
            exec:
              command: 
              - /bin/bash
              - -c
              - mkdir -p /home/stackn/.scaleout && cp -n /stackn.json /home/stackn/.scaleout/stackn.json && chown stackn:stackn /home/stackn/.scaleout/stackn.json && service ssh start
        command: ["/bin/bash"]
        args: ["-c", "sleep 3650d"]
        securityContext:
          allowPrivilegeEscalation: true
        volumeMounts:
        - name: cli-config-vol
          mountPath: /home/stackn/.scaleout
        - name: cli-config
          mountPath: /stackn.json
          subPath: stackn.json
        {{- range $key, $value := .Values.apps.volume }}
        - name: {{ $key }}
          mountPath: /home/stackn/{{ $key }}
        {{- end }}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
      - name: cli-config-vol
        emptyDir: {}
      - name: cli-config
        configMap:
          name: {{ .Release.Name }}-cli-config
      {{- range $key, $value := .Values.apps.volume }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}

