apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wetty
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    release: {{ .Release.Name }}
