apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Values.appname }}
            servicePort: 80
  tls:
    - secretName: prod-ingress
      hosts:
        - {{ .Release.Name }}.{{ .Values.global.domain }}