namespace: default
volumes: {}


## Path where PV would be mounted on the MinIO Pod
mountPath: ""
## Override the root directory which the minio server should serve from.
## If left empty, it defaults to the value of {{ .Values.mountPath }}
## If defined, it must be a sub-directory of the path specified in {{ .Values.mountPath }}
##
bucketRoot: "/data"

credentials:
  access_key: minio-access-key
  secret_key: minio-secret-key


ingress:
  v1beta1: false
  secretName: prod-ingress

appconfig:
  apiServerPort: 9000
  uiConsolePort: 9001
  ftpPort: 8022
  image: minio/minio:latest

podSecurityContext:
  seccompProfile:
      type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all

