# Generated by Django 5.1.4 on 2026-08-28 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_Model_tags",
        ),
    ]
