# Generated by Django 5.2.16 on 2026-09-06 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_Model_tags",
        ),
    ]
