# Generated by Django 5.0.2 on 2024-09-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0011_jupyterinstance_environment"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="app",
            field=models.ForeignKey(
                help_text="App associated with the environment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.apps",
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="image",
            field=models.CharField(
                help_text="Image name. Could be like jupyter/minimal-notebook:latest", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(help_text="Display name for the environment for users", max_length=100),
        ),
        migrations.AlterField(
            model_name="environment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project associated with the environment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="repository",
            field=models.CharField(
                blank=True, help_text="Repository name. Could be empty or like ghcr.io", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="slug",
            field=models.CharField(
                blank=True, help_text="This one seem to be legacy and unused", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="public",
            field=models.BooleanField(default=False, help_text="Seems to be legacy and have no effect."),
        ),
    ]
