# Generated by Django 5.1.1 on 2024-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_add_rstudio_environment_to_old_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavor",
            name="cpu_lim",
            field=models.TextField(blank=True, default="2000m", null=True),
        ),
        migrations.AlterField(
            model_name="flavor",
            name="ephmem_lim",
            field=models.TextField(blank=True, default="1000Mi", null=True),
        ),
        migrations.AlterField(
            model_name="flavor",
            name="mem_lim",
            field=models.TextField(blank=True, default="4Gi", null=True),
        ),
    ]
