# Generated by Django 5.1.1 on 2024-10-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_flavor_cpu_lim_alter_flavor_ephmem_lim_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavor",
            name="cpu_lim",
            field=models.TextField(blank=True, default="2000m", null=True, verbose_name="CPU requests"),
        ),
    ]
