# Generated by Django 5.1.1 on 2024-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_flavor_cpu_lim_alter_flavor_cpu_req_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flavor",
            name="ephmem_lim",
            field=models.TextField(blank=True, default="5000Mi", null=True, verbose_name="Ephemeral storage limit"),
        ),
    ]
