# Generated by Django 5.1.4 on 2025-09-11 13:28
import django.db.models.deletion
from django.db import migrations, models, transaction


def normalize_path(path):
    """Normalize instance path for mount path matching."""
    return path.strip().rstrip("/").lower().replace(" ", "")


def populate_mount_paths(apps, schema_editor):
    """Create PersistentVolumeMountPath objects for all volumes and instances."""
    PersistentVolumeMountPath = apps.get_model("projects", "PersistentVolumeMountPath")
    VolumeInstance = apps.get_model("apps", "VolumeInstance")
    CustomAppInstance = apps.get_model("apps", "CustomAppInstance")
    GradioInstance = apps.get_model("apps", "GradioInstance")
    StreamlitInstance = apps.get_model("apps", "StreamlitInstance")
    ShinyInstance = apps.get_model("apps", "ShinyInstance")

    with transaction.atomic():
        # Track mount paths by (volume_id, path) key
        mount_paths_map = {}
        to_create = []

        # Create default mount paths for all volumes
        for volume in VolumeInstance.objects.all():
            for path, is_default in [("/home/data", True), ("/srv/shiny-server/data", False)]:
                key = (volume.id, path)
                mount_paths_map[key] = PersistentVolumeMountPath(volume=volume, mount_path=path, is_default=is_default)
                to_create.append(mount_paths_map[key])

        # Process instances and create mount paths as needed
        instance_queries = [
            (CustomAppInstance, CustomAppInstance.objects.all()),
            (GradioInstance, GradioInstance.objects.all()),
            (StreamlitInstance, StreamlitInstance.objects.all()),
            (ShinyInstance, ShinyInstance.objects.all()),
        ]

        for model_class, queryset in instance_queries:
            for instance in queryset:
                if instance.volume:
                    normalized_path = normalize_path(instance.path)
                    key = (instance.volume.id, normalized_path)

                    if key not in mount_paths_map:
                        mount_paths_map[key] = PersistentVolumeMountPath(
                            volume=instance.volume, mount_path=normalized_path, is_default=False
                        )
                        to_create.append(mount_paths_map[key])

        # Bulk create all mount paths
        if to_create:
            PersistentVolumeMountPath.objects.bulk_create(to_create)


def noop_reverse(apps, schema_editor):
    # Leave data in place on reverse; it's not safe to distinguish rows created by this migration.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0033_alter_customappinstance_description_and_more"),
        ("projects", "0008_project_deleted_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentVolumeMountPath",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mount_path", models.CharField(max_length=512)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mount_paths",
                        to="apps.volumeinstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("volume", "mount_path"), name="uniq_volume_mount_path"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("volume",),
                        name="uniq_default_mount_per_volume",
                    ),
                ],
            },
        ),
        migrations.RunPython(populate_mount_paths, noop_reverse),
    ]
