# Generated by Django 5.1.4 on 2025-09-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0033_alter_customappinstance_description_and_more"),
        ("projects", "0008_project_deleted_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentVolumeMountPaths",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mount_path", models.CharField(max_length=512)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mount_paths",
                        to="apps.volumeinstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("volume", "mount_path"), name="uniq_volume_mount_path"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("volume",),
                        name="uniq_default_mount_per_volume",
                    ),
                ],
            },
        ),
    ]
