# Generated by Django 5.1.4 on 2025-09-11 13:28
from itertools import chain

import django.db.models.deletion
from django.db import migrations, models, transaction


def populate_mount_paths(apps, schema_editor):
    PersistentVolumeMountPaths = apps.get_model("projects", "PersistentVolumeMountPaths")
    VolumeInstance = apps.get_model("apps", "VolumeInstance")
    CustomAppInstance = apps.get_model("apps", "CustomAppInstance")
    GradioInstance = apps.get_model("apps", "GradioInstance")
    StreamlitInstance = apps.get_model("apps", "StreamlitInstance")
    ShinyInstance = apps.get_model("apps", "ShinyInstance")

    with transaction.atomic():
        to_create = []
        for volume in VolumeInstance.objects.all():
            to_create.append(PersistentVolumeMountPaths(volume=volume, mount_path="/home/data", is_default=True))
            to_create.append(
                PersistentVolumeMountPaths(
                    volume=volume,
                    mount_path="/srv/shiny-server/data/",
                    is_default=False,
                )
            )
        for instance in chain(
            CustomAppInstance.objects.all(),
            GradioInstance.objects.all(),
            StreamlitInstance.objects.all(),
            ShinyInstance.objects.all(),
        ):
            if instance.volume:
                to_create.append(
                    PersistentVolumeMountPaths(
                        volume=instance.volume,
                        mount_path=instance.path,
                        is_default=False,
                    )
                )
        if to_create:
            PersistentVolumeMountPaths.objects.bulk_create(to_create)


def noop_reverse(apps, schema_editor):
    # Leave data in place on reverse; it's not safe to distinguish rows created by this migration.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0033_alter_customappinstance_description_and_more"),
        ("projects", "0008_project_deleted_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersistentVolumeMountPaths",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mount_path", models.CharField(max_length=512)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mount_paths",
                        to="apps.volumeinstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("volume", "mount_path"), name="uniq_volume_mount_path"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("volume",),
                        name="uniq_default_mount_per_volume",
                    ),
                ],
            },
        ),
        migrations.RunPython(populate_mount_paths, noop_reverse),
    ]
