# Generated by Django 5.1.4 on 2026-06-23 15:43

from django.db import migrations, models


def normalize_gpu_values(apps, schema_editor):
    """Coerce the free-text gpu_req/gpu_lim values to clean integer strings.

    The columns were nullable text with values like "0"/"1". Before changing the
    column type to a NOT NULL smallint, replace NULL/blank/non-numeric values with
    "0" so the database cast cannot fail and no nulls remain.
    """
    Flavor = apps.get_model("projects", "Flavor")
    for flavor in Flavor.objects.all():
        changed = False
        for field in ("gpu_req", "gpu_lim"):
            value = getattr(flavor, field)
            try:
                normalized = str(max(int(value), 0)) if value not in (None, "") else "0"
            except (TypeError, ValueError):
                normalized = "0"
            if normalized != value:
                setattr(flavor, field, normalized)
                changed = True
        if changed:
            flavor.save(update_fields=["gpu_req", "gpu_lim"])


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_persistentvolumemountpaths"),
    ]

    operations = [
        migrations.RunPython(normalize_gpu_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="flavor",
            name="gpu_lim",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="GPU limit"),
        ),
        migrations.AlterField(
            model_name="flavor",
            name="gpu_req",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="GPU request"),
        ),
    ]
