# Generated by Django 5.2.16 on 2026-08-26 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_alter_flavor_gpu_lim_alter_flavor_gpu_req"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="privileged_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who may use their privileged rights here, besides the owner. Only has an effect for users who are privileged users.",
                related_name="privileged_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
