apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-license
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  cpsign.license: {{ toYaml .Values.prostudio.license | indent 2 }}