default_stages:
- commit
repos:
# general hooks to verify or beautify code
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=5000]
  - id: trailing-whitespace
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    exclude: ^charts/
  - id: detect-private-key
  - id: mixed-line-ending
  - id: end-of-file-fixer
    exclude: static/vendor/|static/wiki/
  - id: pretty-format-json
    exclude: ^fixtures/
    args: [--autofix]


# autoformat code with black formatter
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black

# beautify and sort imports
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    additional_dependencies: [toml]
    exclude: '^(.*?/)?migrations/.*\.py$'


# check code style
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    # exclude added here because the .flake8 settings are not respected by pre-commit --all-files
    exclude: __init__.py|manage.py|settings.py|media/|models/|migrations|.venv|.env|venv|env|__pycache__


# static type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.0
  hooks:
  - id: mypy
    additional_dependencies: [types-requests==2.25.9]
