services:
  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    networks:
      internal_network:
        aliases:
          - db.127.0.0.1.nip.io
    volumes:
      - db-data:/var/lib/postgresql/data

  studio:
    user: "${UID}:${GID}"
    container_name: studio
    build:
      context: .
      target: runtime
    image: stackn:develop
    env_file:
      - .env
    command: ["scripts/wait-for-it.sh", "db:5432", "--", sh, scripts/run_web.sh]
    ports:
      - "8080:8080"
    volumes:
      - .:/app:cached
     # - ${PWD}/cluster.conf:/app/cluster.conf
    depends_on:
      - db
    networks:
      internal_network:
        aliases:
          - studio.127.0.0.1.nip.io
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8080"]
      interval: 1s
      timeout: 2s
      start_period: 100s
      retries: 120

  redis:
    image: redis
    env_file:
      - .env
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
     internal_network:
       aliases:
         - redis.127.0.0.1.nip.io

  rabbit:
    image: rabbitmq
    env_file:
      - .env
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      internal_network:
        aliases:
          - rabbit.127.0.0.1.nip.io

  celery-worker:
    user: "${UID}:${GID}"
    build: .
    container_name: celery-worker
    image: stackn:develop
    env_file:
      - .env
    command: sh ./scripts/run_worker.sh
    volumes:
      - .:/app:cached
      - ${PWD}/cluster.conf:/app/cluster.conf
    links:
      - db
      - studio
      - rabbit
      - redis
    depends_on:
      - db
      - studio
      - rabbit
      - redis
    networks:
      internal_network:
        aliases:
          - celery.127.0.0.1.nip.io

  celery-beat:
    user: "${UID}:${GID}"
    build: .
    container_name: celery-beat
    image: stackn:develop
    env_file:
      - .env
    command: sh ./scripts/run_beat.sh

    volumes:
      - .:/app:cached
      - ${PWD}/cluster.conf:/app/cluster.conf
    links:
      - db
      - studio
      - rabbit
      - redis
    depends_on:
      - db
      - studio
      - rabbit
      - redis
    networks:
      internal_network:
        aliases:
          - celery-beat.127.0.0.1.nip.io

  event-listener:
    user: "${UID}:${GID}"
    container_name: event-listener
    image: ghcr.io/scilifelabdatacentre/serve-event-listener/event-listener:v1.1.1
    env_file:
      - .env
    volumes:
      - ${PWD}/cluster.conf:/home/serve/cluster.conf
    networks:
      internal_network:
        aliases:
          - studio.127.0.0.1.nip.io
    depends_on:
      studio:
        condition: service_healthy
    links:
      - studio
    restart: always


  unit-tests:
    user: "${UID}:${GID}"
    image: stackn:develop
    volumes:
    - .:/app:cached
    command: ["pytest", "-n", "auto"]
    profiles:
      - donotstart
    networks:
      internal_network:
        aliases:
          - studio.127.0.0.1.nip.io

  ui-tests:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    volumes:
      - .:/app
      - "/var/run/docker.sock:/var/run/docker.sock"
    entrypoint: ["/bin/bash", "-c", "npm install . && cypress run"]
    profiles:
      - donotstart
    networks:
      internal_network:

networks:
  internal_network:
    driver: bridge

volumes:
  db-data:
