# Generated by Django 4.2.5 on 2023-11-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsObject",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(default="", max_length=60, primary_key=True, serialize=False)),
                ("body", models.TextField(blank=True, default="", max_length=2024, null=True)),
            ],
        ),
    ]
