# Generated by Django 3.2.11 on 2022-09-13 14:02

import django.db.models.deletion
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsObject',
            fields=[
                ('title', models.CharField(default='News Title', max_length=60, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True, default="", max_length=2024)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
