apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: filemanager
      project: {{ .Values.project.slug }}
      type: app
      pod: filemanager
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: filemanager
        project: {{ .Values.project.slug }}
        networking/allow-internet-egress: "false"
        type: app
        pod: filemanager
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Release.Name }}-filemanager
        image: {{ .Values.appconfig.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: FB_USERNAME
          value: dummyvalue
        - name: FB_PASSWORD
          value: dummyvalue123
        securityContext:
        {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
          - containerPort: {{ .Values.service.port }}
        resources: {}
        volumeMounts:
        {{- range $key, $value := .Values.apps.volumeK8s }}
        - name: {{ $key }}
          mountPath: /srv/{{ $key }}
        {{- end }}
      hostname: {{ .Release.Name }}-filemanager
      restartPolicy: Always
      volumes:
      {{- range $key, $value := .Values.apps.volumeK8s }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
status: {}
