apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10000M"
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.global.protocol }}://{{ .Values.global.auth_domain }}:8080/auth/?release={{ .Values.release }}"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.global.domain }}/accounts/login/?next=$scheme%3A%2F%2F$host"
  name: {{ .Release.Name }}-filemanager-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ .Values.service.name }}
              port:
                number: {{ .Values.service.port }}
          pathType: ImplementationSpecific

  tls:
    - secretName: {{ .Values.ingress.secretName }}
      hosts:
        - {{ .Values.global.domain }}
