# Generated by Django 4.2.7 on 2024-02-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
