# Generated by Django 5.0.2 on 2024-05-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customappinstance",
            name="volume",
        ),
        migrations.AddField(
            model_name="customappinstance",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="apps.volumeinstance",
            ),
        ),
    ]
