# Generated by Django 5.0.2 on 2024-05-16 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tagulous_appinstance_tags",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="AppInstance",
        ),
        migrations.DeleteModel(
            name="Tagulous_AppInstance_tags",
        ),
    ]
