# Generated by Django 4.2.7 on 2024-02-15 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_appinstance_note_on_linkonly_privacy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appinstance",
            name="note_on_linkonly_privacy",
        ),
    ]
