# Generated by Django 4.2.7 on 2024-02-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_remove_appinstance_note_on_linkonly_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
