# Generated by Django 4.2.7 on 2024-03-19 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_appinstance_note_on_linkonly_privacy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apps",
            name="chart_archive",
        ),
    ]
