# Generated by Django 4.2.7 on 2024-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections_module", "0001_initial"),
        ("apps", "0005_appinstance_note_on_linkonly_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstance",
            name="collections",
            field=models.ManyToManyField(blank=True, related_name="app_instances", to="collections_module.collection"),
        ),
    ]
