# Generated by Django 4.2.7 on 2024-03-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_appinstance_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstance",
            name="source_code_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
