# Generated by Django 5.0.2 on 2024-05-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0008_alter_appcategories_options_alter_apps_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyinstance",
            name="proxy",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="port",
            field=models.IntegerField(default=3838),
        ),
    ]
