# Generated by Django 5.0.2 on 2024-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0008_alter_appcategories_options_alter_apps_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdomain",
            name="subdomain",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
