# Generated by Django 5.0.2 on 2024-05-06 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0009_volumeinstance_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jupyterinstance",
            name="app_status",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(class)s", to="apps.appstatus"
            ),
        ),
        migrations.AlterField(
            model_name="volumeinstance",
            name="app_status",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(class)s", to="apps.appstatus"
            ),
        ),
        migrations.RemoveField(
            model_name="resourcedata",
            name="appinstance",
        ),
        migrations.RemoveField(
            model_name="appstatus",
            name="appinstance",
        ),
        migrations.RemoveField(
            model_name="appstatus",
            name="status_type",
        ),
        migrations.AddField(
            model_name="appstatus",
            name="status",
            field=models.CharField(default="Unknown", max_length=15),
        ),
        migrations.DeleteModel(
            name="AppStatusNew",
        ),
        migrations.DeleteModel(
            name="ResourceData",
        ),
    ]
