# Generated by Django 4.2.5 on 2023-11-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_environment_public_projecttemplate_enabled_and_more"),
        ("apps", "0013_appinstance_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstance",
            name="flavor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="appinstance", to="projects.flavor"
            ),
        ),
    ]
