name: default

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip=23.0.1
  - pip:
    - mlflow==2.2.1
    - numpy==1.23.5
    - matplotlib==3.7.1
    - pandas==1.5.3
    - scipy==1.10.1
    - scikit-learn==1.2.1
    - cloudpickle==2.2.1
    - boto3==1.26.89

