apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-exp
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    release: {{ .Release.Name }}