# Generated by Django 5.1.4 on 2025-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_emailsendingtable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsendingtable",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin/email/account-enabled-email.html", "admin/email/account-enabled-email.html"),
                    ("admin/email/base.html", "admin/email/base.html"),
                    (
                        "admin/email/user-in-not-from-a-swedish-uni.html",
                        "admin/email/user-in-not-from-a-swedish-uni.html",
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
