# Generated by Django 5.1.4 on 2025-08-29 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_emailsendingtable_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationtable",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
