# Generated by Django 4.2.7 on 2024-04-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_fixtureversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
