# Generated by Django 5.1.4 on 2025-12-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_emailverificationtable_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsendingtable",
            name="from_email",
            field=models.EmailField(
                choices=[
                    ("noreply-serve@scilifelab.se", "noreply-serve@scilifelab.se"),
                    ("serve@scilifelab.se", "serve@scilifelab.se"),
                ],
                default="serve@scilifelab.se",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="message",
            field=models.TextField(
                blank=True,
                default="Dear X,\n\nKind regards, \nSciLifeLab Serve team",
                help_text="Type your message here if you want to write it manually. Alternatively, choose one of the templates.",
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("failed", "Failed")],
                default="pending",
                help_text="This field will indicate whether the email was successfully sent after you hit 'Save'.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="subject",
            field=models.CharField(
                help_text="Subject of the email. If there already exists a ticket on Edge, you can use its subject to track email history through it.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin/email/account-enabled-email.html", "Account approved/enabled"),
                    ("admin/email/user-not-from-a-swedish-uni.html", "User not from a Swedish uni"),
                ],
                help_text="Select a template if you do not want to type a message manually. If selected, anything in the Message field will be ignored.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="to_email",
            field=models.EmailField(
                help_text="This field will indicate the email to which the email was sent after you hit 'Save'.",
                max_length=254,
            ),
        ),
    ]
