# Generated by Django 5.1.4 on 2025-12-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_emailverificationtable_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsendingtable",
            name="from_email",
            field=models.EmailField(
                choices=[
                    ("noreply-serve@scilifelab.se", "noreply-serve@scilifelab.se"),
                    ("serve@scilifelab.se", "serve@scilifelab.se"),
                ],
                default="serve@scilifelab.se",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="message",
            field=models.TextField(
                default="Dear X,\n\nKind regards, \nSciLifeLab Serve team", help_text="Email message to be sent."
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("failed", "Failed")],
                default="pending",
                help_text="This field will indicate whether the email was successfully sent after you hit 'Save'.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="subject",
            field=models.CharField(
                help_text="Subject of the email. If there already exists a ticket on Edge, you can use its subject to track email history through it.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[("admin/email/base.html", "admin/email/base.html")],
                help_text="Select a template if you want your message to be formatted with html in Serve style. Otherwise it will be plain text",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendingtable",
            name="to_email",
            field=models.EmailField(
                help_text="This field will indicate the email to which the email was sent after you hit 'Save'.",
                max_length=254,
            ),
        ),
    ]
