# Generated by Django 5.1.4 on 2025-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_emailverificationtable_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsendingtable",
            name="from_email",
            field=models.EmailField(
                choices=[
                    ("noreply-serve@scilifelab.se", "noreply-serve@scilifelab.se"),
                    ("serve@scilifelab.se", "serve@scilifelab.se"),
                ],
                default="serve@scilifelab.se",
                max_length=254,
            ),
        ),
    ]
