# Generated by Django 4.2.7 on 2024-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_userprofile_deleted_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceMode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("login_and_signup_disabled", models.BooleanField(default=False)),
                ("message_in_header", models.TextField(blank=True, max_length=1000)),
                ("message_in_footer", models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
