# Generated by Django 5.1.4 on 2025-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_alter_emailsendingtable_from_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsendingtable",
            name="message",
            field=models.TextField(
                blank=True,
                default="<p>Dear X,</p><p>Kind regards,<br>SciLifeLab Serve team</p>",
                help_text="Type your message here if you want to write it manually. Alternatively, choose one of the templates. Supports rich text formatting.",
            ),
        ),
    ]
