# Generated by Django 5.1.4 on 2026-01-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_alter_emailsendingtable_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
