# Generated by Django 5.1.4 on 2026-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_merge_20260108_1042"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
