# Generated by Django 5.1.4 on 2026-02-17 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_alter_emailsendingtable_from_email"),
        ("common", "0008_migrate_affiliation_to_organization"),
    ]

    operations = []
