# Generated by Django 5.1.4 on 2026-02-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_migrate_affiliation_to_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="orcid_access_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="orcid_id",
            field=models.CharField(
                blank=True, default="", help_text="Authenticated ORCID iD, format: 0000-0002-1234-5678", max_length=25
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="orcid_refresh_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="orcid_token_scope",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
