# Generated by Django 5.1.4 on 2026-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_merge_20260217_1419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsendingtable",
            name="from_email",
            field=models.EmailField(
                choices=[
                    ("noreply-serve@scilifelab.se", "noreply-serve@scilifelab.se"),
                    ("serve@scilifelab.se", "serve@scilifelab.se"),
                ],
                default="serve@scilifelab.se",
                max_length=254,
            ),
        ),
    ]
