# Generated by Django 5.1.4 on 2026-03-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_add_affiliations_remove_legacy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancemode",
            name="message_in_project_dashboard",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
