# Generated by Django 5.1.4 on 2026-02-20 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_userprofile_orcid_access_token_userprofile_orcid_id_and_more"),
        ("common", "0010_alter_emailsendingtable_from_email"),
    ]

    operations = []
