# Generated by Django 5.2.16 on 2026-08-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_maintenancemode_message_in_project_dashboard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"permissions": [("privileged_user", "Has privileged user rights")]},
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_privileged",
            field=models.BooleanField(
                default=False,
                help_text="Lets the user exceed the project and app limits, expand project volumes, and manage flavors and environments. The 'Privileged users' group has the same effect.",
                verbose_name="Privileged user",
            ),
        ),
    ]
