apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ $.Release.Name }}
      app: {{ .Values.appname }}
      project: {{ $.Values.project.slug }}
      type: app
      pod: {{ .Values.appname }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        # prometheus.io/port: "8501"
      labels:
        release: {{ $.Release.Name }}
        app: {{ .Values.appname }}
        project: {{ $.Values.project.slug }}
        networking/allow-internet-egress: "true"
        networking/allow-egress-to-studio-web: "true"
        type: app
        pod: {{ .Values.appname }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.appconfig.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.service.targetport }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.flavor | nindent 10 }}
         {{- if .Values.apps.volumeK8s }}
        volumeMounts:
        {{- range $key, $value := .Values.apps.volumeK8s }}
        - name: {{ $key }}
          mountPath: {{ $.Values.appconfig.path }}
        {{- end }}
        {{- end }}
        - name: tmp-empty
          mountPath: /tmp
        - name: {{ .Release.Name }}-tissuumaps-configmap
          mountPath: /tissuumaps.cfg
          subPath: tissuumaps.cfg
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      {{ if .Values.apps.volumeK8s }}
      volumes:
      {{- range $key, $value := .Values.apps.volumeK8s }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $value.release }}
      {{- end }}
      {{ end }}
      - name: tmp-empty
        emptyDir: {}
      - name: {{ .Release.Name }}-tissuumaps-configmap
        configMap:
          name: {{ .Release.Name }}-tissuumaps-configmap
          items:
          - key: tissuumaps.cfg
            path: tissuumaps.cfg
