apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vscode
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-vscode
spec:
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8080
  selector:
    release: {{ $.Release.Name }}