apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .Values.appname }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    release: {{ $.Release.Name }}