namespace: default
appname: rstudio
project:
  name: project
  slug: project-slug

global:
  protocol: TCP

apps:
  volumek8s:

appconfig:
  port: 8787
  image: ghcr.io/scilifelabdatacentre/serve-rstudio:latest

resources:
  requests:
    ephemeral-storage: "50Mi"
    cpu: 1.0
  limits:
    ephemeral-storage: "400Mi"
    cpu: 1.0

gpu:
  enabled: false

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: acceleration
          operator: In
          values:
          - gpu

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress
  
podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all







service:
  name: customapp-svc

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress
  
podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all
