replicas: 1
appname: tensorflow-serving
namespace: default
visibility: private

resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 700m
    memory: 2Gi

registry:
  secure: False
  host: stack-docker-registry:5000

imagePullSecret: regcred

project:
  slug: project-slug

deployment:
  image: ghcr.io/scilifelabdatacentre/serve-tensorflow:230214-0820
  version: version
  name: deployment-name
  endpoint: deployment-endpoint
  path: deployment-path
  port: 8501

context:
  image: context-image

hpa:
  enabled: false
  min_pods: 1
  max_pods: 3
  cpu_target: 60

model:
  name: name
  version: version
  release_type: release_type
  description: short-description
  url: url
  access_key: key
  secret_key: secret
  bucket: bucket
  obj: obj

s3:
  skip_tls: true

model_card:
  enabled: false
  path: model-card

ingress:
  v1beta1: false

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
