namespace: default
appname: tissuumaps
project:
  name: project
  slug: project-slug

global:
  protocol: TCP

apps:
  volumek8s:

appconfig:
  #port: 80 Instead uses the port and target port defined in the fixture
  image: docker.io/cavenel/tissuumaps:3 # ghcr.io/tissuumaps/tissuumaps:3
  path: /mnt/data/

service:
  name: tissuumaps-svc

imagePullSecrets:
  - name: regcred

ingress:
  secretName: prod-ingress

podSecurityContext:
  seccompProfile:
      type: RuntimeDefault
  fsGroup: 1501

securityContext:
  runAsNonRoot: true
  runAsUser: 1501
  runAsGroup: 1501
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all
