apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mlflow-svc
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.appname }}-svc
    app: {{ .Values.appname }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.appconfig.port }}
  selector:
    release: {{ .Release.Name }}
