apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mlflow-svc
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.appname }}-svc
    app: mlflow-serve
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    release: {{ .Release.Name }}