namespace: default
appname: jupyter-lab
project:
  name: project
  slug: project-slug

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: acceleration
          operator: In
          values:
          - gpu

global:
  domain: localhost

apps:
  volumek8s:

imagePullSecrets:
  - name: regcred

minio:
  access_key: minio
  secret_key: minio123
  bucket: dataset

appconfig:
  port: 8888
  image: ghcr.io/scilifelabdatacentre/serve-jupyterlab:231030-1145

service:
  name: jupyterlab-svc

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress

mlflow:
  url: ""
  s3url: ""
  access_key: ""
  secret_key: ""
  region: ""
  username: ""
  password: ""

podSecurityContext:
  seccompProfile:
      type: RuntimeDefault
  fsGroup: 100

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 100
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all
