from .custom import CustomAppInstance, CustomAppInstanceManager
from .dash import DashInstance, DashInstanceManager
from .filemanager import FilemanagerInstance, FilemanagerInstanceManager
from .jupyter import JupyterInstance, JupyterInstanceManager
from .netpolicy import NetpolicyInstance, NetpolicyInstanceManager
from .rstudio import RStudioInstance, RStudioInstanceManager
from .shiny import ShinyInstance, ShinyInstanceManager
from .tissuumaps import TissuumapsInstance, TissuumapsInstanceManager
from .volume import VolumeInstance, VolumeInstanceManager
from .vscode import VSCodeInstance, VSCodeInstanceManager
