from .custom import CustomAppInstance, CustomAppInstanceManager
from .custom.gradio import GradioAppInstanceManager, GradioInstance
from .custom.streamlit import StreamlitAppInstanceManager, StreamlitInstance
from .dash import DashInstance, DashInstanceManager
from .depictio import DepictioAppManager, DepictioInstance
from .filemanager import FilemanagerInstance, FilemanagerInstanceManager
from .jupyter import JupyterInstance, JupyterInstanceManager
from .mlflow import MlflowAppManager, MLFlowInstance
from .netpolicy import NetpolicyInstance, NetpolicyInstanceManager
from .rstudio import RStudioInstance, RStudioInstanceManager
from .shiny import ShinyInstance, ShinyInstanceManager
from .tissuumaps import TissuumapsInstance, TissuumapsInstanceManager
from .volume import VolumeInstance, VolumeInstanceManager
from .vscode import VSCodeInstance, VSCodeInstanceManager
