version: '3'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - GET_HOSTS_FROM=dns
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      internal_network:
        aliases:
          - db.<your-domain>
    volumes:
      - db-data:/var/lib/postgresql/data

  studio:
    container_name: studio
    build: .
    image: scaleoutsystems/studio-dev:v060
    command: sh scripts/run_web.sh
    environment:
      - GET_HOSTS_FROM=dns
      - KUBECONFIG=/root/.kube/config
      - DJANGO_SUPERUSER_PASSWORD='dGhpaXNhdmVyeW5vdHNhZmVvbmx'
      - DEBUG=true
      - INIT=true
      - FEDN=false
    volumes:
      - .:/app:cached
      - ${PWD}/cluster.conf:/root/.kube/config
    depends_on:
      - db
    networks:
      internal_network:
        aliases:
          - studio.<your-domain>

  ingress:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: scaleoutsystems/ingress:master
    environment:
      - GET_HOSTS_FROM=dns
    container_name: ingress
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
      - ./repos:/var/www/html/git/repos
    ports:
      - 8080:80
    depends_on:
      - studio
    networks:
      internal_network:
        aliases:
          - studio.<your-domain>

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      internal_network:
        aliases:
          - redis.<your-domain>
  
  rabbit:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=LJqEG9RE4FdZbVWoJzZIOQEI
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      internal_network:
        aliases:
          - rabbit.<your-domain>

  celery-worker:
    build: .
    container_name: celery-worker
    image: scaleoutsystems/studio-dev:v060
    command: sh ./scripts/run_worker.sh
    environment:
      - KUBECONFIG=/root/.kube/config
      - BASE_PATH=/app
    volumes:
      - .:/app:cached
      - ${PWD}/cluster.conf:/root/.kube/config
    links:
      - db
      - studio
      - rabbit
      - redis
    depends_on:
      - db
      - studio
      - rabbit
      - redis
    networks:
      internal_network:
        aliases:
          - celery.<your-domain>

  celery-beat:
    build: .
    container_name: celery-beat
    image: scaleoutsystems/studio-dev:v060
    command: sh ./scripts/run_beat.sh
    environment:
      - KUBECONFIG=/root/.kube/config
      - BASE_PATH=/app
    volumes:
      - .:/app:cached
      - ${PWD}/cluster.conf:/root/.kube/config
    links:
      - db
      - studio
      - rabbit
      - redis
    depends_on:
      - db
      - studio
      - rabbit
      - redis
    networks:
      internal_network:
        aliases:
          - celery-beat.<your-domain>

networks:
  internal_network:
    driver: bridge

volumes:
  db-data:
    