apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dash
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8050
  selector:
    release: {{ .Release.Name }}-dash