apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lab
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-lab
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  selector:
    release: {{ .Release.Name }}