# Generated by Django 5.0.2 on 2024-04-29 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_project_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="appenv",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="registry",
        ),
    ]
