# Generated by Django 5.0.2 on 2024-05-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0009_shinyinstance_proxy_alter_shinyinstance_port"),
        ("projects", "0003_remove_environment_appenv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplate",
            name="available_apps",
            field=models.ManyToManyField(blank=True, related_name="available_apps", to="apps.apps"),
        ),
    ]
