# Generated by Django 5.0.2 on 2024-05-15 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0002_remove_model_s3"),
        ("projects", "0004_projecttemplate_available_apps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="mlflow",
        ),
        migrations.RemoveField(
            model_name="releasename",
            name="app",
        ),
        migrations.RemoveField(
            model_name="releasename",
            name="project",
        ),
        migrations.RemoveField(
            model_name="s3",
            name="app",
        ),
        migrations.RemoveField(
            model_name="s3",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="s3",
            name="project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s3storage",
        ),
        migrations.DeleteModel(
            name="MLFlow",
        ),
        migrations.DeleteModel(
            name="ReleaseName",
        ),
        migrations.DeleteModel(
            name="S3",
        ),
    ]
