namespace: default
appname: dash-app
project:
  name: project
  slug: project-slug

app:

  resources:
    requests:
      memory: 1024Mi
      cpu: 1.0
    limits:
      memory: 1024Mi
      cpu: 1.0

  gpu:
    enabled: false

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: acceleration
            operator: In
            values:
            - gpu

imagePullSecrets:
  - name: regcred

dash:
  port: 8050

deployment:
  debug: false

ingress:
  secretName: prod-ingress

s3sync:
  image: scaleoutsystems/s3-sync:latest

ingress:
  secretName: prod-ingress
  v1beta1: false