# Generated by Django 4.2.7 on 2024-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="zenodo_community_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
