apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      release: {{ $.Release.Name }}
      app: {{ .Values.appname }}
      project: {{ $.Values.project.slug }}
      type: app
      pod: {{ .Values.appname }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8501"
      labels:
        release: {{ $.Release.Name }}
        app: {{ .Values.appname }}
        project: {{ $.Values.project.slug }}
        networking/allow-internet-egress: "true"
        networking/allow-internet-ingress: "true"
        type: app
        pod: {{ .Values.appname }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: copy-model
        image: minio/mc
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        {{ if .Values.s3.skip_tls }}
        args: ["-c", "mc config host add --insecure projminio $S3_ENDPOINT $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY;mc cp --insecure projminio/$STACKN_MODEL_BUCKET/$STACKN_MODEL_FILE /models/model.tar.gz"]
        {{ else }}
        args: ["-c", "mc config host add projminio $S3_ENDPOINT $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY;mc cp projminio/$STACKN_MODEL_BUCKET/$STACKN_MODEL_FILE /models/model.tar.gz"]
        {{ end }}
        volumeMounts:
        - name: model-vol
          mountPath: /models
        env:
        - name: S3_ACCESS_KEY_ID
          value: {{ .Values.model.access_key }}
        - name: S3_SECRET_ACCESS_KEY
          value: {{ .Values.model.secret_key }}
        - name: S3_ENDPOINT
          value: {{ .Values.model.url }}
        - name: STACKN_MODEL_BUCKET
          value: {{ .Values.model.bucket }}
        - name: STACKN_MODEL_FILE
          value: {{ .Values.model.obj }}
      - name: extract-model
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "cd /models && tar xvf model.tar.gz"]
        volumeMounts:
        - name: model-vol
          mountPath: /models
      containers:
      {{ if .Values.model_card.enabled }}
      - name: model-card
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: model-vol
          mountPath: /models
        - name: mc-conf
          mountPath: /etc/nginx
      {{ end }}
      - name: serve
        image: {{ .Values.appconfig.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.appconfig.port }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.flavor | nindent 10 }}
        volumeMounts:
        - name: model-vol
          mountPath: /models
        env:
        - name: MODEL_NAME
          value: models
      volumes:
      {{ if .Values.model_card.enabled }}
      - name: mc-conf
        configMap:
          name: {{ .Release.Name }}-mc-config
      {{ end }}
      - name: model-vol
        emptyDir: {}
