apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      release: {{ $.Release.Name }}
      app: tensorflow-serving
      project: {{ $.Values.project.slug }}
      type: app
      pod: tensorflow-serving
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8501"
      labels:
        release: {{ $.Release.Name }}
        app: tensorflow-serving
        project: {{ $.Values.project.slug }}
        networking/allow-internet-egress: "true"
        networking/allow-internet-ingress: "true"
        type: app
        pod: tensorflow-serving
    spec:
    {{ if .Values.flavor.gpu.enabled }}
      affinity:
        {{ .Values.labs.affinity | toYaml | nindent 8 | trim }}
    {{ end }}
      automountServiceAccountToken: false
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      volumes:
      - name: rp-conf
        configMap:
          name: {{ .Release.Name }}-rp-config
      {{ if .Values.model_card.enabled }}
      - name: mc-conf
        configMap:
          name: {{ .Release.Name }}-mc-config
      {{ end }}
      - name: model-vol
        emptyDir: {}
      initContainers:
      - name: copy-model
        image: minio/mc
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        {{ if .Values.s3.skip_tls }}
        args: ["-c", "mc config host add --insecure projminio $S3_ENDPOINT $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY;mc cp --insecure projminio/$STACKN_MODEL_BUCKET/$STACKN_MODEL_FILE /models/model.tar.gz"]
        {{ else }}
        args: ["-c", "mc config host add projminio $S3_ENDPOINT $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY;mc cp projminio/$STACKN_MODEL_BUCKET/$STACKN_MODEL_FILE /models/model.tar.gz"]
        {{ end }}
        volumeMounts:
        - name: model-vol
          mountPath: /models
        env:
        - name: S3_ACCESS_KEY_ID
          value: {{ .Values.model.access_key }}
        - name: S3_SECRET_ACCESS_KEY
          value: {{ .Values.model.secret_key }}
        - name: AWS_REGION
          value: us-east-1
        - name: S3_ENDPOINT
          value: {{ .Values.model.url }}
        - name: STACKN_MODEL_BUCKET
          value: {{ .Values.model.bucket }}
        - name: STACKN_MODEL_FILE
          value: {{ .Values.model.obj }}
      - name: extract-model
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "cd /models && tar xvf model.tar.gz"]
        volumeMounts:
        - name: model-vol
          mountPath: /models
      containers:
      - name: reverse-proxy
        image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: Always
        {{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          privileged: {{ .Values.securityContext.privileged }}
          capabilities:
            drop:
              - all
        {{- end }}
        volumeMounts:
        - name: rp-conf
          mountPath: /etc/nginx
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

      {{ if .Values.model_card.enabled }}
      - name: model-card
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: model-vol
          mountPath: /models
        - name: mc-conf
          mountPath: /etc/nginx
      {{ end }}
      - name: serve
        {{- if .Values.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          privileged: {{ .Values.securityContext.privileged }}
          capabilities:
            drop:
              - all
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.flavor.requests.memory | default "256Mi" }}
            cpu: {{ .Values.flavor.requests.cpu | default "200m" }}
            {{ if .Values.flavor.gpu.enabled }}
            nvidia.com/gpu: {{ .Values.flavor.requests.gpu }}
            {{ end }}
          limits:
            memory: {{ .Values.flavor.limits.memory | default "256Mi" }}
            cpu: {{ .Values.flavor.limits.cpu | default "200m" }}
            {{ if .Values.flavor.gpu.enabled }}
            nvidia.com/gpu: {{ .Values.flavor.requests.gpu }}
            {{ end }}
        volumeMounts:
        - name: model-vol
          mountPath: /models
        env:
        - name: MODEL_NAME
          value: models
        image: {{ .Values.deployment.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.deployment.port }}