domain: 192.168.64.2.nip.io
global:
  network: fedn-network
  control:
    helper: keras
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent

environment:
  repository: scaleoutsystems
  image: fedn-reducer:master

reducer:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  v1beta1: false
  secret: prod-ingress
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
