apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-standardapp
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.image_selection.port }}
  selector:
    release: {{ $.Release.Name }}