# Generated by Django 5.0.2 on 2024-05-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collections_module", "0002_collection_zenodo_community_id"),
        ("models", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsObject",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(default="", max_length=60, primary_key=True, serialize=False)),
                ("body", models.TextField(blank=True, default="", max_length=2024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PublicModelObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("obj", models.FileField(upload_to="models/objects/")),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("model", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="models.model")),
            ],
        ),
        migrations.CreateModel(
            name="PublishedModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512)),
                ("pattern", models.CharField(default="", max_length=255)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True, related_name="published_models", to="collections_module.collection"
                    ),
                ),
                ("model_obj", models.ManyToManyField(to="portal.publicmodelobject")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project")),
            ],
        ),
    ]
