# Generated by Django 4.2.7 on 2024-03-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections_module", "0001_initial"),
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedmodel",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="published_models", to="collections_module.collection"
            ),
        ),
    ]
