# Generated by Django 5.0.2 on 2024-05-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_publishedmodel_collections"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsObject",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(default="", max_length=60, primary_key=True, serialize=False)),
                ("body", models.TextField(blank=True, default="", max_length=2024, null=True)),
            ],
        ),
    ]
