apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    release: {{ .Release.Name }}
