replicas: 1
appname: mlflow-serve
namespace: default
visibility: private


global:
  domain: global.domain
  protocol: TCP

project:
  slug: project-slug

appconfig:
  image: ghcr.io/scilifelabdatacentre/serve-mlflow:231030-1149
  port: 5000


context:
  image: context-image

hpa:
  enabled: false
  min_pods: 1
  max_pods: 3
  cpu_target: 60


model:
  name: name
  version: version
  release_type: release_type
  description: short-description
  url: url
  access_key: key
  secret_key: secret
  bucket: bucket
  obj: obj

model_card:
  enabled: false
  path: model-card

ingress:
  v1beta1: false

podSecurityContext:
  seccompProfile:
      type: RuntimeDefault
  fsGroup: 100

securityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all
