apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
    app: minio
    project: {{ .Values.project.slug }}
    type: secret
type: Opaque
data:
  accesskey: {{ randAlphaNum 20 | b64enc | quote }}
  secretkey: {{ randAlphaNum 40 | b64enc | quote }}
