apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20000m"
  name: {{ .Release.Name }}-minio-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-minio
            servicePort: 9000
  tls:
    - secretName: prod-ingress
      hosts:
        - {{ .Values.global.domain }}
