namespace: default
appname: mongo-express
project:
  name: test
  slug: slug

s3sync:
  image: registry.scilifelab.stackn.dev/s3-sync:latest #scaleoutsystems/s3-sync:latest

global:
  domain: local.stackn.dev

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress

apps:
  mongodb:
    app_name:
      release: release-name
      volumes:
        vol_name:
          name: vol_name
          claim: vol_claim_name
      credentials:
        username: admin
        password: password
