namespace: default
appname: mongo-express
project:
  name: project
  slug: slug

s3sync:
  image: scaleoutsystems/s3-sync:latest

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress

apps:
  mongodb:
    app_name:
      release: release-name
      volumes:
        vol_name:
          name: vol_name
          claim: vol_claim_name
      credentials:
        username: admin
        password: password
