apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pull-secret
  namespace: {{ .Values.namespace }}
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        {{- range $firstkey, $firstvalue := .Values.apps.environment }}
        {{- range $key, $value := $firstvalue.apps.docker_registry }}
        {{- $_ := set $ "key" $key }}
        {{- $_ := set $ "value" $value }}
        "{{ $value.release }}.{{ $.Values.global.domain }}": {
          "auth": "{{ tpl ("{{ .value.credentials.username }}:{{ .value.credentials.password }}") $ | b64enc }}"
        }
        {{- end }}
        {{- end }}
      }
    }
type: kubernetes.io/dockerconfigjson