replicas: 1
appname: fedn-client
namespace: default
visibility: private

flavor:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 0.5Gi

global:
  domain: global.domain

registry:
  secure: False
  host: stack-docker-registry:5000

imagePullSecret: regcred

project:
  slug: project-slug

deployment:
  image: scaleoutsystems/default-python-volume:latest
  version: version
  name: deployment-name
  endpoint: deployment-endpoint
  path: deployment-path
  port: 8501

context:
  image: context-image

model:
  name: name
  version: version
  release_type: release_type
  description: short-description
  url: url
  access_key: key
  secret_key: secret
  bucket: bucket
  obj: obj

model_card:
  enabled: false
  path: model-card

ingress:
  v1beta1: false

# extraEnv: |
#   - name: LICENSE_FILE
#     value: SOMESTRING
