namespace: default
appname: shinyapp
project:
  name: project
  slug: project-slug

global:
  protocol: TCP

apps:
  volumek8s:

appconfig:
  port: 8501

service:
  name: customapp-svc

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all


  



