# Generated by Django 5.0.2 on 2024-05-27 07:28

import django.db.models.deletion
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppCategories",
            fields=[
                ("name", models.CharField(max_length=512)),
                ("priority", models.IntegerField(default=100)),
                ("slug", models.CharField(default="", max_length=512, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "App Category",
                "verbose_name_plural": "App Categories",
            },
        ),
        migrations.CreateModel(
            name="AppStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("info", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="Creating", max_length=15)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "App Status",
                "verbose_name_plural": "App Statuses",
                "get_latest_by": "time",
            },
        ),
        migrations.CreateModel(
            name="BaseAppInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chart", models.CharField(max_length=512)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("info", models.JSONField(blank=True, null=True)),
                ("name", models.CharField(default="app_name", max_length=512)),
                ("k8s_values", models.JSONField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "# BASE APP INSTANCE",
                "verbose_name_plural": "# BASE APP INSTANCES",
                "permissions": [("can_access_app", "Can access app service")],
            },
        ),
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subdomain", models.CharField(max_length=53, unique=True)),
            ],
            options={
                "verbose_name": "Subdomain",
                "verbose_name_plural": "Subdomains",
            },
        ),
        migrations.CreateModel(
            name="Tagulous_CustomAppInstance_tags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Internal counter of how many times this tag is in use"),
                ),
                (
                    "protected",
                    models.BooleanField(default=False, help_text="Will not be deleted when the count reaches 0"),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name="Tagulous_DashInstance_tags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Internal counter of how many times this tag is in use"),
                ),
                (
                    "protected",
                    models.BooleanField(default=False, help_text="Will not be deleted when the count reaches 0"),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name="Tagulous_ShinyInstance_tags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Internal counter of how many times this tag is in use"),
                ),
                (
                    "protected",
                    models.BooleanField(default=False, help_text="Will not be deleted when the count reaches 0"),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name="Tagulous_SocialMixin_tags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Internal counter of how many times this tag is in use"),
                ),
                (
                    "protected",
                    models.BooleanField(default=False, help_text="Will not be deleted when the count reaches 0"),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name="Tagulous_TissuumapsInstance_tags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Internal counter of how many times this tag is in use"),
                ),
                (
                    "protected",
                    models.BooleanField(default=False, help_text="Will not be deleted when the count reaches 0"),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name="Apps",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_can_create", models.BooleanField(default=True)),
                ("user_can_edit", models.BooleanField(default=True)),
                ("user_can_delete", models.BooleanField(default=True)),
                ("access", models.CharField(blank=True, default="public", max_length=20, null=True)),
                ("chart", models.CharField(max_length=512)),
                ("chart_archive", models.FileField(blank=True, null=True, upload_to="apps/")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("logo", models.CharField(blank=True, max_length=512, null=True)),
                ("name", models.CharField(max_length=512)),
                ("priority", models.IntegerField(default=100)),
                ("revision", models.IntegerField(default=1)),
                ("settings", models.JSONField(blank=True, null=True)),
                ("slug", models.CharField(blank=True, max_length=512, null=True)),
                ("table_field", models.JSONField(blank=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        to="apps.appcategories",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Template",
                "verbose_name_plural": "App Templates",
            },
        ),
    ]
