# Generated by Django 5.0.2 on 2024-07-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseappinstance",
            name="subdomain",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s",
                to="apps.subdomain",
            ),
        ),
    ]
