# Generated by Django 5.0.2 on 2024-07-23 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdomain",
            name="project",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="projects.project"),
        ),
    ]
