# Generated by Django 5.0.2 on 2024-07-30 13:44

import tagulous.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customappinstance",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                help_text="Add keywords to help categorize your app",
                to="apps.tagulous_customappinstance_tags",
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                help_text="Add keywords to help categorize your app",
                to="apps.tagulous_dashinstance_tags",
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                help_text="Add keywords to help categorize your app",
                to="apps.tagulous_shinyinstance_tags",
            ),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                blank=True,
                help_text="Add keywords to help categorize your app",
                to="apps.tagulous_tissuumapsinstance_tags",
            ),
        ),
    ]
