# Generated by Django 5.0.2 on 2024-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customappinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jupyterinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private")], default="project", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="rstudioinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private")], default="project", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vscodeinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private")], default="project", max_length=20
            ),
        ),
    ]
