# Generated by Django 5.0.2 on 2024-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_alter_customappinstance_tags_alter_dashinstance_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customappinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jupyterinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private")], default="project", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="rstudioinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private")], default="project", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vscodeinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private")], default="project", max_length=20
            ),
        ),
    ]
