# Generated by Django 5.0.2 on 2024-08-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_alter_customappinstance_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyinstance",
            name="allow_container_reuse",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shinyinstance",
            name="minimum_seats_available",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="shinyinstance",
            name="seats_per_container",
            field=models.IntegerField(default=3),
        ),
    ]
