# Generated by Django 5.0.2 on 2024-08-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_alter_customappinstance_access_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subdomain",
            name="is_created_by_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="baseappinstance",
            name="subdomain",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="apps.subdomain",
            ),
        ),
        migrations.AlterField(
            model_name="subdomain",
            name="project",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
    ]
