# Generated by Django 5.0.2 on 2024-08-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_shinyinstance_allow_container_reuse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyinstance",
            name="path",
            field=models.CharField(default="/", max_length=255),
        ),
        migrations.AddField(
            model_name="shinyinstance",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="apps.volumeinstance",
            ),
        ),
    ]
