# Generated by Django 5.0.2 on 2024-08-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_shinyinstance_path_shinyinstance_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shinyinstance",
            name="allow_container_reuse",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="minimum_seats_available",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="seats_per_container",
            field=models.IntegerField(default=1),
        ),
    ]
