# Generated by Django 5.0.2 on 2024-08-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0008_alter_shinyinstance_allow_container_reuse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customappinstance",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="apps.volumeinstance",
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="apps.volumeinstance",
            ),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="apps.volumeinstance",
            ),
        ),
    ]
