# Generated by Django 5.0.2 on 2024-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0009_alter_customappinstance_volume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyinstance",
            name="shiny_site_dir",
            field=models.CharField(default="", max_length=255),
        ),
    ]
