# Generated by Django 5.0.2 on 2024-08-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0009_alter_customappinstance_volume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyinstance",
            name="shiny_app_path",
            field=models.CharField(default="/", max_length=255),
        ),
    ]
