# Generated by Django 5.0.2 on 2024-09-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0010_shinyinstance_shiny_site_dir"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jupyterinstance",
            name="environment",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="projects.environment"
            ),
        ),
    ]
