# Generated by Django 5.0.2 on 2024-09-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0011_jupyterinstance_environment"),
        ("projects", "0003_alter_environment_rename_jupyter_lab_to_default_jupyter"),
    ]

    operations = [
        migrations.AddField(
            model_name="rstudioinstance",
            name="environment",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="projects.environment"
            ),
        ),
    ]
