# Generated by Django 5.1.1 on 2024-09-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0013_alter_customappinstance_tags_alter_dashinstance_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customappinstance",
            name="path",
            field=models.CharField(blank=True, default="/", max_length=255),
        ),
    ]
