# Generated by Django 5.1.1 on 2024-10-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0016_tagulous_streamlitinstance_tags_streamlitinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamlitinstance",
            name="port",
            field=models.IntegerField(default=8000),
        ),
    ]
