# Generated by Django 5.1.1 on 2024-11-19 13:27

import apps.models.app_types.custom.custom
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0017_alter_streamlitinstance_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="customappinstance",
            name="default_url_subpath",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[apps.models.app_types.custom.custom.validate_default_url_subpath],
            ),
        ),
    ]
