# Generated by Django 5.1.1 on 2025-01-19 19:45

import apps.models.app_types.custom.custom
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0020_alter_jupyterinstance_environment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashinstance",
            name="default_url_subpath",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[apps.models.app_types.custom.custom.validate_default_url_subpath],
            ),
        ),
    ]
