# Generated by Django 5.1.1 on 2025-02-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0021_dashinstance_default_url_subpath"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLFlowInstance",
            fields=[
                (
                    "baseappinstance_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apps.baseappinstance",
                    ),
                ),
                ("access", models.CharField(choices=[("project", "Project")], default="project", max_length=20)),
            ],
            options={
                "verbose_name": "MLFlow App Instance",
                "verbose_name_plural": "MLFlow App Instances",
                "permissions": [("can_access_app", "Can access app service")],
            },
            bases=("apps.baseappinstance",),
        ),
        migrations.AddField(
            model_name="apps",
            name="user_can_see_secrets",
            field=models.BooleanField(default=False),
        ),
    ]
