# Generated by Django 5.1.1 on 2024-12-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0021_k8suserappstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseappinstance",
            name="k8s_user_app_status",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="apps.k8suserappstatus",
            ),
        ),
        migrations.AlterField(
            model_name="k8suserappstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("CrashLoopBackOff", "CrashLoopBackOff"),
                    ("ContainerCreating", "ContainerCreating"),
                    ("PodInitializing", "PodInitializing"),
                    ("ErrImagePull", "ErrImagePull"),
                    ("ImagePullBackOff", "ImagePullBackOff"),
                    ("PostStartHookError", "PostStartHookError"),
                    ("Unknown", "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
