# Generated by Django 5.1.1 on 2024-12-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0021_dashinstance_default_url_subpath"),
    ]

    operations = [
        migrations.CreateModel(
            name="K8sUserAppStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("info", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(max_length=15, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "k8s User App Status",
                "verbose_name_plural": "k8s User App Statuses",
                "get_latest_by": "time",
            },
        ),
    ]
