# Generated by Django 5.1.1 on 2025-02-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0021_dashinstance_default_url_subpath"),
    ]

    operations = [
        migrations.AddField(
            model_name="apps",
            name="gpu_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
