# Generated by Django 5.1.1 on 2025-02-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0022_mlflowinstance_apps_user_can_see_secrets"),
    ]

    operations = [
        migrations.AddField(
            model_name="apps",
            name="gpu_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
