# Generated by Django 5.1.1 on 2024-12-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0022_baseappinstance_k8s_user_app_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseappinstance",
            name="latest_user_action",
            field=models.CharField(
                choices=[
                    ("Creating", "Creating"),
                    ("Changing", "Changing"),
                    ("Deleting", "Deleting"),
                    ("Redeploying", "Redeploying"),
                ],
                default="Creating",
                max_length=15,
            ),
        ),
    ]
