# Generated by Django 5.1.1 on 2025-02-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0022_mlflowinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlflowinstance",
            name="access",
            field=models.CharField(choices=[("project", "Project")], default="project", max_length=20),
        ),
    ]
