# Generated by Django 5.1.1 on 2025-02-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0023_apps_gpu_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseappinstance",
            name="upload_size",
            field=models.PositiveIntegerField(default=100, help_text="Max upload size in MB"),
        ),
    ]
