# Generated by Django 5.1.1 on 2024-12-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0023_apps_gpu_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="K8sUserAppStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("info", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(max_length=15, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "k8s User App Status",
                "verbose_name_plural": "k8s User App Statuses",
                "get_latest_by": "time",
            },
        ),
        migrations.AddField(
            model_name="baseappinstance",
            name="latest_user_action",
            field=models.CharField(
                choices=[
                    ("Creating", "Creating"),
                    ("Changing", "Changing"),
                    ("Deleting", "Deleting"),
                    ("SystemDeleting", "SystemDeleting"),
                    ("Redeploying", "Redeploying"),
                ],
                default="Creating",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="baseappinstance",
            name="k8s_user_app_status",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="apps.k8suserappstatus",
            ),
        ),
        migrations.AlterField(
            model_name="k8suserappstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("CrashLoopBackOff", "CrashLoopBackOff"),
                    ("ContainerCreating", "ContainerCreating"),
                    ("PodInitializing", "PodInitializing"),
                    ("ErrImagePull", "ErrImagePull"),
                    ("ImagePullBackOff", "ImagePullBackOff"),
                    ("PostStartHookError", "PostStartHookError"),
                    ("Unknown", "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
