# Generated by Django 5.1.1 on 2025-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0023_mlflowinstance_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="apps",
            name="user_can_see_secrets",
            field=models.BooleanField(default=False),
        ),
    ]
