# Generated by Django 5.1.1 on 2025-01-29 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0024_baseappinstance_latest_user_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashinstance",
            name="default_url_subpath",
        ),
    ]
