# Generated by Django 5.1.1 on 2025-02-05 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0026_dashinstance_default_url_subpath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseappinstance",
            name="app_status",
        ),
    ]
