# Generated by Django 5.1.1 on 2025-02-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0027_remove_baseappinstance_app_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseappinstance",
            name="latest_user_action",
            field=models.CharField(
                choices=[
                    ("Creating", "Creating"),
                    ("Changing", "Changing"),
                    ("Deleting", "Deleting"),
                    ("SystemDeleting", "SystemDeleting"),
                    ("Redeploying", "Redeploying"),
                ],
                default="Creating",
                max_length=15,
            ),
        ),
    ]
