# Generated by Django 5.1.1 on 2025-02-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0027_remove_baseappinstance_app_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseappinstance",
            name="upload_size",
            field=models.PositiveIntegerField(default=100, help_text="Max upload size in MB"),
        ),
    ]
