# Generated by Django 5.1.1 on 2025-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0028_baseappinstance_upload_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shinyinstance",
            name="path",
            field=models.CharField(blank=True, default="/", max_length=255),
        ),
    ]
