# Generated by Django 5.1.1 on 2025-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0030_alter_baseappinstance_k8s_user_app_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseappinstance",
            name="k8s_values_override",
            field=models.JSONField(
                blank=True,
                help_text="Override k8s values for this app instance.This follows general logic of k8s values: if this field is set, then first k8s_values is used, then k8s_values_override. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="baseappinstance",
            name="k8s_values",
            field=models.JSONField(
                blank=True,
                help_text="k8s values for this app instance. It's not possible to change this field directly as it's set automatically on model save. In order to change it, use k8s_values_override.",
                null=True,
            ),
        ),
    ]
