# Generated by Django 5.1.1 on 2025-05-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0031_baseappinstance_k8s_values_override_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubdomainAdmin",
            fields=[
                (
                    "subdomain_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apps.subdomain",
                    ),
                ),
            ],
            bases=("apps.subdomain",),
        ),
    ]
