# Generated by Django 5.1.1 on 2025-06-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0031_baseappinstance_k8s_values_override_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depictioinstance",
            name="access",
            field=models.CharField(
                choices=[("public", "Public"), ("project", "Project"), ("link", "Link"), ("private", "Private")],
                default="project",
                max_length=20,
            ),
        ),
    ]
