# Generated by Django 5.1.1 on 2025-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0032_subdomainadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="k8suserappstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("CrashLoopBackOff", "CrashLoopBackOff"),
                    ("ContainerCreating", "ContainerCreating"),
                    ("PodInitializing", "PodInitializing"),
                    ("ErrImagePull", "ErrImagePull"),
                    ("ImagePullBackOff", "ImagePullBackOff"),
                    ("PostStartHookError", "PostStartHookError"),
                    ("Unknown", "Unknown"),
                    ("Running", "Running"),
                    ("Deleted", "Deleted"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
