# Generated by Django 5.1.1 on 2025-08-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0032_alter_depictioinstance_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customappinstance",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="depictioinstance",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="gradioinstance",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="streamlitinstance",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
