# Generated by Django 5.1.4 on 2025-11-07 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0033_alter_customappinstance_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volumeinstance",
            name="size",
            field=models.IntegerField(
                default=1,
                help_text="Size in GB",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
    ]
