# Generated by Django 5.1.4 on 2025-09-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0033_alter_customappinstance_description_and_more"),
        ("projects", "0009_persistentvolumemountpaths"),
    ]

    operations = [
        migrations.AddField(
            model_name="customappinstance",
            name="mount_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.persistentvolumemountpath",
            ),
        ),
        migrations.AddField(
            model_name="gradioinstance",
            name="mount_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.persistentvolumemountpath",
            ),
        ),
        migrations.AddField(
            model_name="streamlitinstance",
            name="mount_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.persistentvolumemountpath",
            ),
        ),
    ]
