# Generated by Django 5.1.4 on 2025-10-10 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0034_customappinstance_mount_path_and_more"),
        ("projects", "0009_persistentvolumemountpaths"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyinstance",
            name="mount_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.persistentvolumemountpath",
            ),
        ),
    ]
