# Generated by Django 5.1.4 on 2025-10-10 14:49

import django.db.models.deletion
from django.db import migrations, models, transaction


def normalize_path(path):
    """Normalize instance path for mount path matching."""
    return path.strip().rstrip("/").lower().replace(" ", "")


def assign_mount_paths_to_shiny(apps, schema_editor):
    """Assign mount paths to ShinyInstance."""
    PersistentVolumeMountPath = apps.get_model("projects", "PersistentVolumeMountPath")
    ShinyInstance = apps.get_model("apps", "ShinyInstance")

    with transaction.atomic():
        # Build mapping of (volume_id, normalized_path) -> mount_path_id
        mount_paths_map = {}
        for mp in PersistentVolumeMountPath.objects.select_related("volume").all():
            normalized_path = normalize_path(mp.mount_path)
            key = (mp.volume_id, normalized_path)
            mount_paths_map[key] = mp.id

        # Process ShinyInstance
        instances_to_update = []
        for instance in ShinyInstance.objects.select_related("volume").all():
            if instance.volume:
                normalized_path = normalize_path(instance.path)
                key = (instance.volume.id, normalized_path)
                if key in mount_paths_map:
                    instance.mount_path_id = mount_paths_map[key]
                    instances_to_update.append(instance)

        if instances_to_update:
            ShinyInstance.objects.bulk_update(instances_to_update, ["mount_path_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0034_customappinstance_mount_path_and_more"),
        ("projects", "0009_persistentvolumemountpaths"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyinstance",
            name="mount_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.persistentvolumemountpath",
            ),
        ),
        migrations.RunPython(assign_mount_paths_to_shiny, migrations.RunPython.noop),
    ]
