# Generated by Django 5.1.4 on 2025-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0035_customappinstance_app_text_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customappinstance",
            name="app_text_language",
        ),
        migrations.RemoveField(
            model_name="customappinstance",
            name="creator_role",
        ),
        migrations.RemoveField(
            model_name="gradioinstance",
            name="app_text_language",
        ),
        migrations.RemoveField(
            model_name="gradioinstance",
            name="creator_role",
        ),
        migrations.RemoveField(
            model_name="streamlitinstance",
            name="app_text_language",
        ),
        migrations.RemoveField(
            model_name="streamlitinstance",
            name="creator_role",
        ),
        migrations.AddField(
            model_name="baseappinstance",
            name="app_text_language",
            field=models.CharField(
                choices=[("en", "English"), ("sv", "Swedish"), ("other", "Other")], default="en", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="baseappinstance",
            name="creator_role",
            field=models.CharField(
                choices=[
                    ("ContactPerson", "Contact Person"),
                    ("DataCollector", "Data Collector"),
                    ("DataCurator", "Data Curator"),
                    ("DataManager", "Data Manager"),
                    ("Distributor", "Distributor"),
                    ("Editor", "Editor"),
                    ("HostingInstitution", "Hosting Institution"),
                    ("Producer", "Producer"),
                    ("ProjectLeader", "Project Leader"),
                    ("ProjectManager", "Project Manager"),
                    ("ProjectMember", "Project Member"),
                    ("RegistrationAgency", "Registration Agency"),
                    ("RegistrationAuthority", "Registration Authority"),
                    ("RelatedPerson", "Related Person"),
                    ("Researcher", "Researcher"),
                    ("ResearchGroup", "Research Group"),
                    ("RightsHolder", "Rights Holder"),
                    ("Sponsor", "Sponsor"),
                    ("Supervisor", "Supervisor"),
                    ("Translator", "Translator"),
                    ("WorkPackageLeader", "Work Package Leader"),
                    ("Other", "Other"),
                ],
                default="ContactPerson",
                max_length=60,
            ),
        ),
    ]
