# Generated by Django 5.1.4 on 2025-11-14 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0034_alter_volumeinstance_size"),
        ("apps", "0035_shinyinstance_mount_path"),
    ]

    operations = []
