# Generated by Django 5.1.4 on 2025-12-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0036_merge_20251114_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="customappinstance",
            name="reminder_date_linkonly_privacy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dashinstance",
            name="reminder_date_linkonly_privacy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="depictioinstance",
            name="reminder_date_linkonly_privacy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gradioinstance",
            name="reminder_date_linkonly_privacy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shinyinstance",
            name="reminder_date_linkonly_privacy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="streamlitinstance",
            name="reminder_date_linkonly_privacy",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tissuumapsinstance",
            name="reminder_date_linkonly_privacy",
            field=models.DateField(blank=True, null=True),
        ),
    ]
