# Generated by Django 5.1.4 on 2025-10-01 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0036_remove_customappinstance_app_text_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseappinstance",
            name="app_text_language",
        ),
        migrations.RemoveField(
            model_name="baseappinstance",
            name="creator_role",
        ),
    ]
