# Generated by Django 5.1.4 on 2025-12-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0037_customappinstance_reminder_date_linkonly_privacy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        db_index=True,
                        help_text="Registered task identifier (e.g., 'validate_docker_image')",
                        max_length=255,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("validation", "Validation"),
                            ("external_api", "External API"),
                            ("post_deploy", "Post Deploy"),
                        ],
                        db_index=True,
                        default="validation",
                        help_text="Category of the task",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the task",
                        max_length=50,
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="If True, failure of this task will block deployment",
                    ),
                ),
                (
                    "execution_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which task should run. Lower numbers run first. Tasks with same order run in parallel.",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        help_text="JSON data containing task output/results",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if task failed",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this task has been retried",
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum number of retry attempts",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the task was created",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task execution started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task execution completed",
                        null=True,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Celery task ID for tracking",
                        max_length=255,
                    ),
                ),
                (
                    "app_instance",
                    models.ForeignKey(
                        help_text="The app instance this task is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_tasks",
                        to="apps.baseappinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Background Task",
                "verbose_name_plural": "Background Tasks",
                "ordering": ["execution_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["app_instance", "status"],
                        name="apps_backgr_app_ins_idx",
                    ),
                    models.Index(
                        fields=["task_name", "status"],
                        name="apps_backgr_task_na_idx",
                    ),
                    models.Index(
                        fields=["created_at"],
                        name="apps_backgr_created_idx",
                    ),
                ],
            },
        ),
    ]
