# Generated by Django 5.1.4 on 2025-10-15 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        #("apps", "0035_shinyinstance_mount_path"),
        ("apps", "0037_remove_baseappinstance_app_text_language_and_more"),
    ]

    operations = []
