# Generated by Django 5.1.4 on 2025-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0037_customappinstance_reminder_date_linkonly_privacy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseappinstance",
            name="app_doi",
            field=models.CharField(
                blank=True, help_text="Digital Object Identifier for the published app", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="baseappinstance",
            name="invenio_record_id",
            field=models.CharField(
                blank=True, help_text="Invenio record identifier for published apps", max_length=255, null=True
            ),
        ),
    ]
