# Generated by Django 5.1.4 on 2026-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0038_baseappinstance_app_doi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseappinstance",
            name="name",
            field=models.CharField(default="app_name", max_length=512, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="customappinstance",
            name="description",
            field=models.TextField(
                default="",
                help_text="Provide a detailed description of your app. Think of it as the abstract of a research article.",
            ),
        ),
        migrations.AlterField(
            model_name="customappinstance",
            name="image",
            field=models.CharField(
                help_text="Docker image with your application. For example, ghcr.io/username/image-name:image-tag or docker.io/username/image-name:image-tag.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="customappinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note that this option can be used only for a limited amount of time. For example, while the app is under development or while an accompanying article is under peer review. Describe why you need to choose the Link only permission level.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customappinstance",
            name="port",
            field=models.IntegerField(
                default=8000,
                help_text="Port that the Docker container exposes and the application runs on. This should be an integer between 3000-9999.",
            ),
        ),
        migrations.AlterField(
            model_name="customappinstance",
            name="source_code_url",
            field=models.URLField(
                blank=True,
                help_text="Provide a link to the public source code of the application. For example, https://github.com/ScilifelabDataCentre/streamlit-image-to-smiles.",
                null=True,
                verbose_name="Source code URL",
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                help_text="The chosen Permission level determines who can access the application.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="description",
            field=models.TextField(
                default="",
                help_text="Provide a detailed description of your app. Think of it as the abstract of a research article.",
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="image",
            field=models.CharField(
                help_text="Docker image with your application. For example, ghcr.io/username/image-name:image-tag or docker.io/username/image-name:image-tag.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note that this option can be used only for a limited amount of time. For example, while the app is under development or while an accompanying article is under peer review. Describe why you need to choose the Link only permission level.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="port",
            field=models.IntegerField(
                default=8000,
                help_text="Port that the Docker container exposes and the application runs on. This should be an integer between 3000-9999.",
            ),
        ),
        migrations.AlterField(
            model_name="dashinstance",
            name="source_code_url",
            field=models.URLField(
                blank=True,
                help_text="Provide a link to the public source code of the application. For example, https://github.com/ScilifelabDataCentre/streamlit-image-to-smiles.",
                null=True,
                verbose_name="Source code URL",
            ),
        ),
        migrations.AlterField(
            model_name="depictioinstance",
            name="description",
            field=models.TextField(
                default="",
                help_text="Provide a detailed description of your app. Think of it as the abstract of a research article.",
            ),
        ),
        migrations.AlterField(
            model_name="depictioinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note that this option can be used only for a limited amount of time. For example, while the app is under development or while an accompanying article is under peer review. Describe why you need to choose the Link only permission level.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depictioinstance",
            name="source_code_url",
            field=models.URLField(
                blank=True,
                help_text="Provide a link to the public source code of the application. For example, https://github.com/ScilifelabDataCentre/streamlit-image-to-smiles.",
                null=True,
                verbose_name="Source code URL",
            ),
        ),
        migrations.AlterField(
            model_name="gradioinstance",
            name="description",
            field=models.TextField(
                default="",
                help_text="Provide a detailed description of your app. Think of it as the abstract of a research article.",
            ),
        ),
        migrations.AlterField(
            model_name="gradioinstance",
            name="image",
            field=models.CharField(
                help_text="Docker image with your application. For example, ghcr.io/username/image-name:image-tag or docker.io/username/image-name:image-tag.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="gradioinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note that this option can be used only for a limited amount of time. For example, while the app is under development or while an accompanying article is under peer review. Describe why you need to choose the Link only permission level.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gradioinstance",
            name="port",
            field=models.IntegerField(
                default=7860,
                help_text="Port that the Docker container exposes and the application runs on. This should be an integer between 3000-9999.",
            ),
        ),
        migrations.AlterField(
            model_name="gradioinstance",
            name="source_code_url",
            field=models.URLField(
                blank=True,
                help_text="Provide a link to the public source code of the application. For example, https://github.com/ScilifelabDataCentre/streamlit-image-to-smiles.",
                null=True,
                verbose_name="Source code URL",
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="description",
            field=models.TextField(
                default="",
                help_text="Provide a detailed description of your app. Think of it as the abstract of a research article.",
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="image",
            field=models.CharField(
                help_text="Docker image with your application. For example, ghcr.io/username/image-name:image-tag or docker.io/username/image-name:image-tag.",
                max_length=255,
                verbose_name="Docker image",
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note that this option can be used only for a limited amount of time. For example, while the app is under development or while an accompanying article is under peer review. Describe why you need to choose the Link only permission level.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="port",
            field=models.IntegerField(
                default=3838,
                help_text="Port that the Docker container exposes and the application runs on. This should be an integer between 3000-9999.",
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="source_code_url",
            field=models.URLField(
                blank=True,
                help_text="Provide a link to the public source code of the application. For example, https://github.com/ScilifelabDataCentre/streamlit-image-to-smiles.",
                null=True,
                verbose_name="Source code URL",
            ),
        ),
        migrations.AlterField(
            model_name="streamlitinstance",
            name="description",
            field=models.TextField(
                default="",
                help_text="Provide a detailed description of your app. Think of it as the abstract of a research article.",
            ),
        ),
        migrations.AlterField(
            model_name="streamlitinstance",
            name="image",
            field=models.CharField(
                help_text="Docker image with your application. For example, ghcr.io/username/image-name:image-tag or docker.io/username/image-name:image-tag.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="streamlitinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note that this option can be used only for a limited amount of time. For example, while the app is under development or while an accompanying article is under peer review. Describe why you need to choose the Link only permission level.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="streamlitinstance",
            name="port",
            field=models.IntegerField(
                default=8000,
                help_text="Port that the Docker container exposes and the application runs on. This should be an integer between 3000-9999.",
            ),
        ),
        migrations.AlterField(
            model_name="streamlitinstance",
            name="source_code_url",
            field=models.URLField(
                blank=True,
                help_text="Provide a link to the public source code of the application. For example, https://github.com/ScilifelabDataCentre/streamlit-image-to-smiles.",
                null=True,
                verbose_name="Source code URL",
            ),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="description",
            field=models.TextField(
                default="",
                help_text="Provide a detailed description of your app. Think of it as the abstract of a research article.",
            ),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="note_on_linkonly_privacy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note that this option can be used only for a limited amount of time. For example, while the app is under development or while an accompanying article is under peer review. Describe why you need to choose the Link only permission level.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="source_code_url",
            field=models.URLField(
                blank=True,
                help_text="Provide a link to the public source code of the application. For example, https://github.com/ScilifelabDataCentre/streamlit-image-to-smiles.",
                null=True,
                verbose_name="Source code URL",
            ),
        ),
    ]
