# Generated by Django 5.1.4 on 2025-11-18 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0034_alter_volumeinstance_size"),
        ("apps", "0038_merge_20251015_1608"),
    ]

    operations = []
