# Generated by Django 5.1.4 on 2025-12-17 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0038_background_task"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="backgroundtask",
            new_name="apps_backgr_app_ins_d4a941_idx",
            old_name="apps_backgr_app_ins_idx",
        ),
        migrations.RenameIndex(
            model_name="backgroundtask",
            new_name="apps_backgr_task_na_f4e99c_idx",
            old_name="apps_backgr_task_na_idx",
        ),
        migrations.RenameIndex(
            model_name="backgroundtask",
            new_name="apps_backgr_created_14ab5c_idx",
            old_name="apps_backgr_created_idx",
        ),
    ]
