# Generated by Django 5.1.4 on 2026-02-17 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0039_alter_baseappinstance_name_and_more"),
        ("apps", "0039_rename_apps_backgr_app_ins_idx_apps_backgr_app_ins_d4a941_idx_and_more"),
    ]

    operations = []
