# Generated by Django 5.1.4 on 2026-02-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0039_alter_baseappinstance_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseappinstance",
            name="app_doi",
        ),
        migrations.RemoveField(
            model_name="baseappinstance",
            name="invenio_record_id",
        ),
        migrations.AddField(
            model_name="customappinstance",
            name="app_doi",
            field=models.CharField(
                blank=True, help_text="Digital Object Identifier for the published app", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="customappinstance",
            name="invenio_record_id",
            field=models.CharField(
                blank=True, help_text="Invenio record identifier for published apps", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="customappinstance",
            name="made_public_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dashinstance",
            name="app_doi",
            field=models.CharField(
                blank=True, help_text="Digital Object Identifier for the published app", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="dashinstance",
            name="invenio_record_id",
            field=models.CharField(
                blank=True, help_text="Invenio record identifier for published apps", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="dashinstance",
            name="made_public_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="depictioinstance",
            name="app_doi",
            field=models.CharField(
                blank=True, help_text="Digital Object Identifier for the published app", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="depictioinstance",
            name="invenio_record_id",
            field=models.CharField(
                blank=True, help_text="Invenio record identifier for published apps", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="depictioinstance",
            name="made_public_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gradioinstance",
            name="app_doi",
            field=models.CharField(
                blank=True, help_text="Digital Object Identifier for the published app", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="gradioinstance",
            name="invenio_record_id",
            field=models.CharField(
                blank=True, help_text="Invenio record identifier for published apps", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="gradioinstance",
            name="made_public_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shinyinstance",
            name="app_doi",
            field=models.CharField(
                blank=True, help_text="Digital Object Identifier for the published app", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="shinyinstance",
            name="invenio_record_id",
            field=models.CharField(
                blank=True, help_text="Invenio record identifier for published apps", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="shinyinstance",
            name="made_public_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="streamlitinstance",
            name="app_doi",
            field=models.CharField(
                blank=True, help_text="Digital Object Identifier for the published app", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="streamlitinstance",
            name="invenio_record_id",
            field=models.CharField(
                blank=True, help_text="Invenio record identifier for published apps", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="streamlitinstance",
            name="made_public_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tissuumapsinstance",
            name="app_doi",
            field=models.CharField(
                blank=True, help_text="Digital Object Identifier for the published app", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tissuumapsinstance",
            name="invenio_record_id",
            field=models.CharField(
                blank=True, help_text="Invenio record identifier for published apps", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tissuumapsinstance",
            name="made_public_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
