# Generated by Django 5.1.4 on 2025-11-18 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0036_merge_20251114_1402"),
        ("apps", "0039_merge_20251118_1328"),
    ]

    operations = []
