# Generated by Django 5.1.4 on 2026-03-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0041_remove_baseappinstance_app_doi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundtask",
            name="run_id",
            field=models.UUIDField(
                blank=True,
                help_text="Identifier shared by all background tasks created for the same deployment run.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundtask",
            index=models.Index(fields=["app_instance", "run_id"], name="apps_backgr_app_ins_babd2f_idx"),
        ),
    ]
