# Generated by Django 5.1.4 on 2026-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0041_remove_baseappinstance_app_doi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customappinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                help_text="The chosen Permission level determines who can access the application.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="depictioinstance",
            name="access",
            field=models.CharField(
                choices=[("public", "Public"), ("project", "Project"), ("link", "Link"), ("private", "Private")],
                default="project",
                help_text="The chosen Permission level determines who can access the application.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gradioinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                help_text="The chosen Permission level determines who can access the application.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shinyinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                help_text="The chosen Permission level determines who can access the application.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="streamlitinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                help_text="The chosen Permission level determines who can access the application.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tissuumapsinstance",
            name="access",
            field=models.CharField(
                choices=[("project", "Project"), ("private", "Private"), ("public", "Public"), ("link", "Link")],
                default="project",
                help_text="The chosen Permission level determines who can access the application.",
                max_length=20,
            ),
        ),
    ]
