# Generated by Django 5.1.4 on 2026-06-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0042_alter_customappinstance_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customappinstance",
            name="subjects_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select research field(s) and keyword(s) to help categorize your app.",
            ),
        ),
        migrations.AddField(
            model_name="dashinstance",
            name="subjects_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select research field(s) and keyword(s) to help categorize your app.",
            ),
        ),
        migrations.AddField(
            model_name="depictioinstance",
            name="subjects_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select research field(s) and keyword(s) to help categorize your app.",
            ),
        ),
        migrations.AddField(
            model_name="gradioinstance",
            name="subjects_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select research field(s) and keyword(s) to help categorize your app.",
            ),
        ),
        migrations.AddField(
            model_name="shinyinstance",
            name="subjects_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select research field(s) and keyword(s) to help categorize your app.",
            ),
        ),
        migrations.AddField(
            model_name="streamlitinstance",
            name="subjects_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select research field(s) and keyword(s) to help categorize your app.",
            ),
        ),
        migrations.AddField(
            model_name="tissuumapsinstance",
            name="subjects_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Select research field(s) and keyword(s) to help categorize your app.",
            ),
        ),
    ]
