# Generated by Django 5.1.4 on 2026-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_customappinstance_subjects_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseappinstance',
            name='latest_user_action',
            field=models.CharField(choices=[('Creating', 'Creating'), ('Changing', 'Changing'), ('Deleting', 'Deleting'), ('SystemDeleting', 'SystemDeleting'), ('Redeploying', 'Redeploying'), ('Draft', 'Draft')], default='Creating', max_length=15),
        ),
        migrations.AlterField(
            model_name='customappinstance',
            name='access',
            field=models.CharField(choices=[('draft', 'Draft'), ('project', 'Project'), ('private', 'Private'), ('public', 'Public'), ('link', 'Link')], default='draft', help_text='The chosen Permission level determines who can access the application.', max_length=20),
        ),
        migrations.AlterField(
            model_name='dashinstance',
            name='access',
            field=models.CharField(choices=[('draft', 'Draft'), ('project', 'Project'), ('private', 'Private'), ('public', 'Public'), ('link', 'Link')], default='draft', help_text='The chosen Permission level determines who can access the application.', max_length=20),
        ),
        migrations.AlterField(
            model_name='gradioinstance',
            name='access',
            field=models.CharField(choices=[('draft', 'Draft'), ('project', 'Project'), ('private', 'Private'), ('public', 'Public'), ('link', 'Link')], default='draft', help_text='The chosen Permission level determines who can access the application.', max_length=20),
        ),
        migrations.AlterField(
            model_name='shinyinstance',
            name='access',
            field=models.CharField(choices=[('draft', 'Draft'), ('project', 'Project'), ('private', 'Private'), ('public', 'Public'), ('link', 'Link')], default='draft', help_text='The chosen Permission level determines who can access the application.', max_length=20),
        ),
        migrations.AlterField(
            model_name='streamlitinstance',
            name='access',
            field=models.CharField(choices=[('draft', 'Draft'), ('project', 'Project'), ('private', 'Private'), ('public', 'Public'), ('link', 'Link')], default='draft', help_text='The chosen Permission level determines who can access the application.', max_length=20),
        ),
    ]
