# Generated by Django 5.1.4 on 2026-08-28 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0043_customappinstance_subjects_keywords_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tagulous_AbstractCustomAppInstance_tags",
        ),
        migrations.AlterUniqueTogether(
            name="tagulous_customappinstance_tags",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="customappinstance",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="tagulous_dashinstance_tags",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dashinstance",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="tagulous_depictioinstance_tags",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="depictioinstance",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="tagulous_gradioinstance_tags",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="gradioinstance",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="tagulous_shinyinstance_tags",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shinyinstance",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_SocialMixin_tags",
        ),
        migrations.AlterUniqueTogether(
            name="tagulous_streamlitinstance_tags",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="streamlitinstance",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="tagulous_tissuumapsinstance_tags",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tissuumapsinstance",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_CustomAppInstance_tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_DashInstance_tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_DepictioInstance_tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_GradioInstance_tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_ShinyInstance_tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_StreamlitInstance_tags",
        ),
        migrations.DeleteModel(
            name="Tagulous_TissuumapsInstance_tags",
        ),
    ]
