# Generated by Django 5.2.16 on 2026-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0043_customappinstance_subjects_keywords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volumeinstance",
            name="previous_size",
            field=models.IntegerField(
                blank=True,
                help_text="Size before the most recent resize, until the cluster confirms or refuses it.",
                null=True,
            ),
        ),
    ]
