name: Build studio and ingress

on:
  push:
    branches:
      - serve-0.6
    paths:
    - 'components/studio/**'
  pull_request:
    branches:
      - serve-0.6
    paths:
    - 'components/studio/**'
  release:
    types: [published]

jobs:
 
  build-containers:
    if: github.repository == 'scilifelabdatacentre/stackn'
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2     

      - name: Setup variables
        id: wf-vars
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          VERSION=${GITHUB_REF##*-}
          IMAGE_NAME="studio"
          echo "BASE_BRANCH=${BASE_BRANCH}"
          echo "IMAGE_TAG=${IMAGE_TAG}"
          echo ::set-output name=IMAGE_NAME::$IMAGE_NAME
          echo ::set-output name=IMAGE_TAG::$IMAGE_TAG
    
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push studio
        uses: docker/build-push-action@v2
        with:
          context: components/studio/
          push: "${{ github.event_name != 'pull_request' }}"
          tags: ghcr.io/${{ github.repository }}/${{ steps.wf-vars.outputs.IMAGE_NAME }}:${{ steps.wf-vars.outputs.IMAGE_TAG }}
          file: components/studio/Dockerfile
        
      - name: docker build ingress
        uses: docker/build-push-action@v2
        with:
          context: components/studio/
          push: "${{ github.event_name != 'pull_request' }}"
          tags: ghcr.io/${{ github.repository }}/ingress:${{ steps.wf-vars.outputs.IMAGE_TAG }}
          file: components/studio/Dockerfile.nginx
