name: Code checks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]

jobs:
  check-code:

    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          #Python version should be the same as the base image in Dockerfile
          python-version: "3.8.10"
      - name: Install dependencies
        
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
      - name: Check Python imports
        run: |
          isort . --check --diff --skip migrations --profile black -p studio --line-length 79
      - name: Check Python formatting
        run: |
          black . --check --diff --line-length 79 --exclude migrations
      - name: Check Python linting
        run: |
          flake8 .  --exclude migrations
