name: Pre-commit linters and code checks

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'

jobs:
  pre_commit:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pre-commit==3.7.1

    - name: Run pre-commit
      run: pre-commit run --all-files
