apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-shinyproxy-configmap
  labels:
    {{- include "shinyproxy.labels" . | nindent 4 }}
data:
  application.yml: |
    management:
      server:
        port: 9091
    server:
      secure-cookies: true
    proxy:
      authentication: none
      container-backend: kubernetes
      heartbeat-rate: 10000
      heartbeat-timeout: 60000
      kubernetes:
        internal-networking: true
        namespace: {{ .Values.namespace }}
        image-pull-policy: IfNotPresent
      hide-navbar: true
      landing-page: /app/{{ .Release.Name }}
      livenessProbe: {}
      logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
      port: {{ .Values.appconfig.proxyport }}
      readinessProbe: {}
      same-site-cookie: None
      specs:
      - container-cmd:
        - /usr/bin/shiny-server
        container-cpu-limit: {{ .Values.flavor.limits.cpu }}
        container-cpu-request: {{ .Values.flavor.requests.cpu }}
        container-image: {{ .Values.appconfig.image }}
        container-memory-limit: {{ .Values.flavor.limits.memory }}
        container-memory-request: {{ .Values.flavor.requests.memory }}
        port: {{ .Values.appconfig.port }}
        id:  {{ .Release.Name }}
        display-name: {{ .Values.app_name }}
        description: {{ .Values.app_description }}
        labels:
          sp.instance: {{ .Release.Name }}
          allow-internet-egress: "true"
          shinyproxy-app: {{ .Release.Name }}
        kubernetes-pod-patches: |
          - op: add
            path: /spec/securityContext
            value:
              runAsUser: 999
              runAsGroup: 999
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              privileged: false
      title: Serve Shiny Proxy
