apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Release.Name }}-shinyapp
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.appconfig.proxyport }}
  selector:
    release: {{ $.Release.Name }}
