# Generated by Django 5.0.2 on 2024-05-15 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="s3",
        ),
    ]
