namespace: default
volumes: {}

ingress:
  v1beta1: false
  secretName: prod-ingress

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false